### ISSUE TITLE
Great and amibitious project!

### ISSUE THREAD

**Issue by AlexandraOM** [fac18/week8-denk#35]
This looks really good and I'm impressed with how many pages you have, how you've tried to ensure people are logged in, in order to show them more pages (with the session id and prepperId) would love to be able to make a profile so I could get logged in too!

**Comment by Ayub3** [comment]
Love the design, reminds me of I am a legend, cant wait to make a profile.😎

**Comment by redwedge** [comment]
`[](https://media.giphy.com/media/fjyGsdRkYqb3j1WODz/giphy.gif)
