### ISSUE TITLE
Testing! 

### ISSUE THREAD

**Issue by Albadylic** [fac18/week8-denk#36]
You've got some great tests written. Really cool to see you testing a DB post :medal_sports: 

When I run npm test though, they don't run :cry: 

I can run your server tests and see a couple of failing tests for the single-prep and single-prepper routes (lines 38-58).

And one more thing...

Can you see the redundancy in this code? :thinking: 

```test("/single-prep will load with 200", t => {
  request(app)
    .get("/single-prep")
    .expect(200)
    .end((err, res) => {
      t.error(err);
      t.deepEqual(res.statusCode, 200, "/single-prep should load with 200");
      t.end();
    });
});```

**Comment by Albadylic** [comment]
I've just found that the reason your DB tests don't run is to do with the imports at the top! :mailbox_with_mail:

**Comment by AlexandraOM** [comment]
Single-prepper works when given it's current end-point at /profile!
```/single-prepper will load with 200

    ✔ null
    ✔ /single-prepper should load with 200```

Congrats on the tests guys and the TDD 👍🏻

**Comment by redwedge** [comment]
Thank you both for the pro tips! We will make adjustments :)
