### ISSUE TITLE
Impressive use of promises, and short-cuts

### ISSUE THREAD

**Issue by AlexandraOM** [fac18/week8-denk#39]
Clean code
![](https://media.giphy.com/media/SJ36g0617Nh60/giphy.gif)

Impressed by the use of `exports.get` `exports.get` and promisifying your requests 👏🏼💪🏼take some time to share this knowledge in your presentation!

**Comment by Albadylic** [comment]
Retweet ^^^ 🍪😄

**Comment by redwedge** [comment]
Thank you we definitely (especially the _Promise.all_, such fun)
